language: java

addons:
  sonarcloud:
    organization: "grpc-swagger"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: grpc-swagger